jupyter nbconvert "01 - Introduction.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "01 - Introduction.ipynb" 
jupyter nbconvert "02 - The Reader.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "02 - The Reader.ipynb" 
jupyter nbconvert "03 - The Interpreter.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "03 - The Interpreter.ipynb" 
jupyter nbconvert "04 - The Framework.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "04 - The Framework.ipynb" 
jupyter nbconvert "05 - Queue.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "05 - Queue.ipynb" 
jupyter nbconvert "06 - IDE.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "06 - IDE.ipynb" 
jupyter nbconvert "Appendix - A - Literate Programming.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "Appendix - A - Literate Programming.ipynb" 
jupyter nbconvert "Appendix - B - Utilities.ipynb" --to notebook --ClearOutputPreprocessor.enabled=True --output "Appendix - B - Utilities.ipynb" 
